'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class WeatherPredictionEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=WeatherPredictionEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Cities() As DbSet(Of Cities)
    Public Overridable Property Clothes() As DbSet(Of Clothes)
    Public Overridable Property ClothesImages() As DbSet(Of ClothesImages)
    Public Overridable Property Crops() As DbSet(Of Crops)
    Public Overridable Property Places() As DbSet(Of Places)
    Public Overridable Property PlacesImages() As DbSet(Of PlacesImages)
    Public Overridable Property WeatherData2() As DbSet(Of WeatherData2)

End Class
