'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cities
    Public Property City_ID As Integer
    Public Property City_Name As String

    Public Overridable Property WeatherData2 As ICollection(Of WeatherData2) = New HashSet(Of WeatherData2)

End Class
Partial Public Class Clothes
    Public Property SeasonID As Integer
    Public Property SeasonName As String
    Public Property MinTemp As Nullable(Of Integer)
    Public Property MaxTemp As Nullable(Of Integer)

    Public Overridable Property ClothesImages As ICollection(Of ClothesImages) = New HashSet(Of ClothesImages)
    Public Overridable Property WeatherData2 As ICollection(Of WeatherData2) = New HashSet(Of WeatherData2)

End Class
Partial Public Class ClothesImages
    Public Property ClothesID As Integer
    Public Property ImageURL As String
    Public Property SeasonID As Nullable(Of Integer)

    Public Overridable Property Clothes As Clothes

End Class
Partial Public Class Crops
    Public Property Crop_ID As Integer
    Public Property Crop_Name_Eng As String
    Public Property Crop_Name_Arabic As String
    Public Property MinTemp As Nullable(Of Integer)
    Public Property MaxTemp As Nullable(Of Integer)
    Public Property ImageURL As String
    Public Property Description As String

    Public Overridable Property WeatherData2 As ICollection(Of WeatherData2) = New HashSet(Of WeatherData2)

End Class
Partial Public Class Places
    Public Property City_ID As Integer
    Public Property City_Name As String
    Public Property Description_Eng As String
    Public Property Description_Arabic As String

    Public Overridable Property PlacesImages As ICollection(Of PlacesImages) = New HashSet(Of PlacesImages)
    Public Overridable Property WeatherData2 As ICollection(Of WeatherData2) = New HashSet(Of WeatherData2)

End Class
Partial Public Class PlacesImages
    Public Property PlaceID As Integer
    Public Property ImageURL As String
    Public Property CityID As Nullable(Of Integer)
    Public Property PlaceName As String

    Public Overridable Property Places As Places

End Class
Partial Public Class WeatherData2
    Public Property WeatherData_ID As Integer
    Public Property Location As String
    Public Property Year As Nullable(Of Double)
    Public Property Month As String
    Public Property Day As Nullable(Of Double)
    Public Property Temp_high As Nullable(Of Double)
    Public Property Temp_avg As Nullable(Of Double)
    Public Property Temp_low As Nullable(Of Double)
    Public Property Dew_Point_high As Nullable(Of Double)
    Public Property Dew_Point_avg As Nullable(Of Double)
    Public Property Dew_Point_low As Nullable(Of Double)
    Public Property Humidity_high As Nullable(Of Double)
    Public Property Humidity_avg As Nullable(Of Double)
    Public Property Humidity_low As Nullable(Of Double)
    Public Property Sea_Level_Press_high As Nullable(Of Double)
    Public Property Sea_Level_Press_avg As Nullable(Of Double)
    Public Property Sea_Level_Press_low As Nullable(Of Double)
    Public Property Visibility_high As Nullable(Of Double)
    Public Property Visibility_avg As Nullable(Of Double)
    Public Property Visibility_low As Nullable(Of Double)
    Public Property Wind_high As Nullable(Of Double)
    Public Property Wind_avg As Nullable(Of Double)
    Public Property Wind_low As Nullable(Of Double)
    Public Property sum As Nullable(Of Double)
    Public Property Events As String
    Public Property City_ID As Nullable(Of Integer)
    Public Property Crop_ID As Nullable(Of Integer)
    Public Property Clothes_ID As Nullable(Of Integer)

    Public Overridable Property Cities As Cities
    Public Overridable Property Clothes As Clothes
    Public Overridable Property Crops As Crops
    Public Overridable Property Places As Places

End Class
